# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Playwright

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    services:
      mariadb:
        image: mariadb:10.6
        ports:
          - 32768:3306
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_USER: root
          MYSQL_PASSWORD: ninja
          MYSQL_DATABASE: ninja
          MYSQL_ROOT_PASSWORD: ninja
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3
      redis:
        image: redis
        ports:
          - 6379/tcp
        options: --health-cmd="redis-cli ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Clone invoiceninja/invoiceninja repository (v5-develop branch) in invoiceninja/ folder
        uses: actions/checkout@v2
        with:
          repository: invoiceninja/invoiceninja
          ref: v5-develop
          path: invoiceninja

      - name: Start MariaDB service
        run: |
          sudo systemctl start mysql.service
      
      - name: Verify MariaDB connection
        env:
          DB_PORT: ${{ job.services.mariadb.ports[3306] }}
          DB_PORT1: ${{ job.services.mariadb.ports[3306] }}

      run: |
        while ! mysqladmin ping -h"127.0.0.1" -P"$DB_PORT" --silent; do
          sleep 1
        done

      - name: Setup and install PHP 8.2
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: mysql, mysqlnd, sqlite3, bcmath, gmp, gd, curl, zip, openssl, mbstring, xml, redis

      - name: Install Composer
        run: |
          curl -sS https://getcomposer.org/installer | php
          mv composer.phar /usr/local/bin/composer
      
      - name: Install dependencies
        run: |
          cd invoiceninja
          composer config -g github-oauth.github.com ${{ secrets.GITHUB_TOKEN }}
          composer install
          
      - name: Setup .env file
        run: |
          cd invoiceninja
          cp .env.ci .env

      - name: Prepare and migrate Invoice Ninja
        env:
          REDIS_PORT: ${{ job.services.redis.ports['6379'] }}
        run: |
          cd invoiceninja
          php artisan key:generate
          php artisan config:clear
          php artisan ninja:post-update
          php artisan optimize
          php artisan migrate:fresh --seed --force && php artisan db:seed --force

